### ISSUE TITLE
wipp 

### ISSUE THREAD

**Issue by sunjunlishi** [jordi-adell/mcarray#1]
wipp could be built in windows?

and mcarry so on.
![qq 20171027131818](https://user-images.githubusercontent.com/11845664/32089318-e1c7a7f8-bb1b-11e7-84e0-b70e57205a6b.png)

**Comment by jordi-adell** [comment]
Hi @sunjunlishi , 

McArray will not compile unless wipp and dspone are available. So it is good that you start from WIPP.
Actually, Windows is not supported, I do not probide specific compilation tools for windows, but you should be able to compile it without major problems; because the code itself it is compatible. 
Look like VS It is trying to compile WIPP against Intel IPP libraries and you probably do not have them. 

Before I can help you further I need to know if you are trying to compile WIPP using cmake support in Visual Studio 2017, or something different.

Regards,

**Comment by sunjunlishi** [comment]
vs2015.to compile wipp ,i have down IPP, not completely  yet

**Comment by sunjunlishi** [comment]
could ubuntu  ok? i am testing in  ubuntu .

**Comment by sunjunlishi** [comment]
ubuntu not ok
-- RELEASE mode. Optimisation flags: 
-- Found FFTW: /usr/local/lib/libfftw3.a  
-- IPP found
-- FFTW found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
IPP_LIB_AC
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_CP
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_DI
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_GEN
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_J
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_M
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_R
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_SC
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_SR
    linked by target "wipp" in directory /home/sun/wipp-master
IPP_LIB_VC
    linked by target "wipp" in directory /home/sun/wipp-master

-- Configuring incomplete, errors occurred!
See also "/home/sun/wipp-master/build/CMakeFiles/CMakeOutput.log".

**Comment by sunjunlishi** [comment]
and  make errror:
In file included from /home/sun/wipp-master/src/wipp/wipputils.cpp:25:0:
/home/sun/wipp-master/src/wipp/ipp/ipputils.inl:106:59: error: expected ‘,’ or ‘...’ before ‘*’ token
   void copyBuffer(const float *inbuffer, int16_t uint32_t *outbuffer, size_t le
                                                           ^
/home/sun/wipp-master/src/wipp/ipp/ipputils.inl: In function ‘void wipp::copyBuffer(const float*, int16_t)’:
/home/sun/wipp-master/src/wipp/ipp/ipputils.inl:108:38: error: ‘outbuffer’ was not declared in this scope
     ippsConvert_32f16u_Sfs(inbuffer, outbuffer, length, ippRndFinancial, 0);
                                      ^
/home/sun/wipp-master/src/wipp/ipp/ipputils.inl:108:49: error: ‘length’ was not declared in this scope
     ippsConvert_32f16u_Sfs(inbuffer, outbuffer, length, ippRndFinancial, 0);
                                                 ^
CMakeFiles/wipp.dir/build.make:62: recipe for target 'CMakeFiles/wipp.dir/src/wipp/wipputils.cpp.o' failed
make[2]: *** [CMakeFiles/wipp.dir/src/wipp/wipputils.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wipp.dir/all' failed
make[1]: *** [CMakeFiles/wipp.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sunjunlishi** [comment]
if i have installed your  deb files, all in.

 libdspone  deb
Library for mathematical calculation signal processing-oriented.
Updated 7 months ago
libdspone-dev  deb
Library for mathematical calculation signal processing-oriented.
Updated 8 months ago
libwipp-dev  deb
Library for mathematical calculation signal processing-oriented.
Updated 8 months ago
libwipp  deb 


but  when i  build mcarray

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find DSPONE (missing: DSPONE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindDSPONE.cmake:16 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:30 (find_package)

I manually copy dspone

**Comment by sunjunlishi** [comment]
I almost succeeded

available (required by /usr/bin/cmake)
CMakeFiles/mcbeam.dir/src/programs/mcabeamf.cpp.o：在函数‘main’中：
mcabeamf.cpp:(.text+0xb76)：对‘dsp::DspGui::DspGui(dsp::ShortTimeProcess&, std::function<void (dsp::ShortTimeProcess&)>&)’未定义的引用
mcabeamf.cpp:(.text+0xbd0)：对‘dsp::DspGui::start(int)’未定义的引用
mcabeamf.cpp:(.text+0xc2e)：对‘dsp::DspGui::~DspGui()’未定义的引用
mcabeamf.cpp:(.text+0xd2e)：对‘dsp::DspGui::~DspGui()’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/mcbeam.dir/build.make:98: recipe for target 'mcbeam-0.3.0' failed
make[2]: *** [mcbeam-0.3.0] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mcbeam.dir/all' failed
make[1]: *** [CMakeFiles/mcbeam.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

i am not using DspGui, and pass 

/home/sun/mcarray-master/src/programs/mcabeamf.cpp:7:0: warning: "DSPONE_GUI" redefined
 #define DSPONE_GUI 0
 ^
<command-line>:0:0: note: this is the location of the previous definition
/usr/bin/cmake: /home/sun/local-builds/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Linking CXX executable mcbeam
/usr/bin/cmake: /home/sun/local-builds/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/sun/local-builds/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/sun/local-builds/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Built target mcbeam
/usr/bin/cmake: /home/sun/local-builds/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)

**Comment by sunjunlishi** [comment]
you have default signal.inl  and fftw3.ok thanks

**Comment by jordi-adell** [comment]
I recommend not using IPP and use FFTw right now. I am working o a IPP implementation that will work with Intel IPP 2017 now.

**Comment by sunjunlishi** [comment]
great wonderful
