### ISSUE TITLE
could you supply audio testing data?

### ISSUE THREAD

**Issue by sunjunlishi** [jordi-adell/mcarray#2]
He's going to help a lot of beginners ，See how strong it is

**Comment by sunjunlishi** [comment]
ok i will recorder myself

**Comment by jordi-adell** [comment]
I cannot supply audio files right now. These is some pending work I have to do. If you record your own and are willing to make it public you are more than welcomed to send it to me and I will add it to the project. Or you can ask for a pull request.

**Comment by sunjunlishi** [comment]
The real dual channel sound card so hard to find, if there is a good effect, I will

**Comment by jordi-adell** [comment]
If you are using only to channels you must use binaural sound separation and localisation algorithms. Delay and sum will do almost nothing if you are using just two channels.

**Comment by sunjunlishi** [comment]
i will have a try. And Your method delay and sum, with 4 channels (linear layout), will have a good effect?
