### ISSUE TITLE
How to strengthen the sound in a certain direction 

### ISSUE THREAD

**Issue by sunjunlishi** [jordi-adell/mcarray#3]
how  to  test.I have built  it.and could you give your testing wav
![1](https://user-images.githubusercontent.com/11845664/32154599-abe1587a-bd6c-11e7-8bab-1c6f1d0a6ece.png)

**Comment by sunjunlishi** [comment]
mcabeamf.cpp->>>>
mca::SourceSeparationAndLocalisation sss(sampleRate, array_description, 1, false);
  auto f_process = std::bind(process_file, _1, snd_file_in, snd_file_out, sf_info_in);

snd_file_out,   What is the output file?

and  Can I strengthen the direction of the sound?





  auto f_process = std::bind(process_file, _1, snd_file_in, snd_file_out, sf_info_in);

**Comment by sunjunlishi** [comment]
ok,input DOA
void Beamformer::processFrame(SignalVector &analysisFrames, SignalPtr outputFrame, double DOA)

**Comment by jordi-adell** [comment]
Right.

**Comment by sunjunlishi** [comment]
![qq 20171106100654](https://user-images.githubusercontent.com/11845664/32422247-4231da1c-c2da-11e7-8d55-3df7b011e0e1.png)

The delay and sum theory I see is the biggest in the 90 degree direction; how does your theory change DOA and increase the energy in this direction, which parameter do you adjust? You can give me you, I don't understand this, with a fishbone in the throat

**Comment by sunjunlishi** [comment]
Fixed beamforming ，i see。What method of fixed beam formation do you use?

**Comment by sunjunlishi** [comment]
Can i strengthen the sound in a certain direction(DOA),not the stronger

**Comment by sunjunlishi** [comment]
If it works, you will be very, very great

**Comment by sunjunlishi** [comment]
you say。Only the one detected with stronger power. my DOA is ok
But my effect is not good, is it the only reason why I have only 4 microphones?span is 0.06m
（In order to test DOA, I use CoolEdit to generate sin waveforms for single source testing; then, single source sound test; two sound source tests, output a DOA information, although alternately, indeed alternate source location is correct. They're all right ）

**Comment by sunjunlishi** [comment]
processFrameSeparation，could you  supply other method ,such  as mvdr

**Comment by jordi-adell** [comment]
Delay and sum with only four microphones cannot do much. Just some enhancement of the source but no completely removal of the background noise.

**Comment by sunjunlishi** [comment]
Hope for a better way.I think it's at the expense of money or sweat

**Comment by jordi-adell** [comment]
Mvdr should not be difficult to implement inside mcarray based on dspone.

**Comment by sunjunlishi** [comment]
thank you
