### ISSUE TITLE
What is the separation method? 

### ISSUE THREAD

**Issue by sunjunlishi** [jordi-adell/mcarray#4]
void Beamformer::processFrame(SignalVector &analysisFrames, SignalPtr outputFrame, double DOA)
{

    wipp::setZeros(outputFrame.get(), _fftCCSLength);
    // Sum all channels multiplied by a phase-ramp according to 
    //the delay to be applied over each one.
    for (int c = 0; c < _nchannels; ++c)
    {
      //	ippsVectorRamp_64f(_phase.get(), 
 _fftCCSLength/2, 0, 
2*M_PI*_sampleRate/(_fftCCSLength-2)/getSpeedOfSound()*_microphonePositions[c]
*cos(DOA+M_PI/2));
	wipp::ramp(_phase.get(), _fftCCSLength/2, 0, 
2*M_PI*_sampleRate/(_fftCCSLength-2)/getSpeedOfSound()*_microphonePositions.getX(c)*co(DOA+M_PI/2));
	wipp::polar2cart(_ones.get(), _phase.get(), 
reinterpret_cast<wipp::wipp_complex_t*>(_complexRamp.get()), _fftCCSLength/2);
	wipp::mult(reinterpret_cast<wipp::wipp_complex_t*>(analysisFrames[c].get()),
		   reinterpret_cast<wipp::wipp_complex_t*>(_complexRamp.get()),
		   reinterpret_cast<wipp::wipp_complex_t*>(_channelSignal.get()),
		   _fftCCSLength/2);
	wipp::add(reinterpret_cast<wipp::wipp_complex_t*>(_channelSignal.get()),
		  reinterpret_cast<wipp::wipp_complex_t*>(outputFrame.get()),
		  _fftCCSLength/2);
    }
    wipp::divC(_nchannels, outputFrame.get(), _fftCCSLength);

}

**Comment by jordi-adell** [comment]
This is the delay and sum beam forming.

**Comment by sunjunlishi** [comment]
If there are two sound sources, is the first sound source separated?

**Comment by jordi-adell** [comment]
Only the one detected with stronger power.

**Comment by sunjunlishi** [comment]
![1](https://user-images.githubusercontent.com/11845664/32427342-e967cf6a-c2fa-11e7-9a69-6f45b8fc5269.png)
![2](https://user-images.githubusercontent.com/11845664/32427357-f2dc7096-c2fa-11e7-9a3a-2aee153337cf.png)

frameAnalysis and frameSynthesis。
What they were using, I tested, and found that they made a distortion of speech

**Comment by sunjunlishi** [comment]
My voice source position is not changed, why DOA value is not regular, what values are there ，Unit cm
![4](https://user-images.githubusercontent.com/11845664/32472806-5e2b87d4-c39f-11e7-88f7-f852615e15b2.png)

**Comment by sunjunlishi** [comment]
if  DOA is not right,the next step will not  right

**Comment by sunjunlishi** [comment]
std::vector<double> mics_positions = {0, 0.05, 0.10, 0.14};
![6](https://user-images.githubusercontent.com/11845664/32480338-2a95c806-c3c9-11e7-9704-3b3cbc7b3f19.png)

3 files in the perspective of the overall change law is not progressive 
Is the position of the microphone the meter?

**Comment by jordi-adell** [comment]
Mic position is the distance between microphones in meters in a linear array.

**Comment by jordi-adell** [comment]
DoA is in degrees.

**Comment by jordi-adell** [comment]
Mic position is the distance between microphones in meters in a linear array.

**Comment by jordi-adell** [comment]
DoA is in degrees.

**Comment by sunjunlishi** [comment]
Is your sound source DOA estimation model for the near field or far field?

**Comment by sunjunlishi** [comment]
![t1](https://user-images.githubusercontent.com/11845664/32533833-a0f39bd0-c48d-11e7-8af0-e2ad7ba5b13b.jpg)
is it  right

**Comment by sunjunlishi** [comment]
My error, our hardware 3, 4 channel back. Your DOA is very accurate, great. I have a few files, if you want, I can give you, send your mailbox, convenient for everyone to test. My array spacing is 0.06m

**Comment by jordi-adell** [comment]
Sorry. I could not answer before. Looks like you are doing a good job. Is DoA is in front means zero degrees.

**Comment by jordi-adell** [comment]
Also, yes. I am very interested in the test signals. And also in the description of your hardware.

**Comment by jordi-adell** [comment]
Please, send the audio files to adellj@gmail.com . Thank you.

**Comment by DWtiangu** [comment]
> My error, our hardware 3, 4 channel back. Your DOA is very accurate, great. I have a few files, if you want, I can give you, send your mailbox, convenient for everyone to test. My array spacing is 0.06m

大佬能吧你的测试音频结果发给我看看么，这个项目能做4麦线性阵列的定向拾音吗
