### ISSUE TITLE
Accuracy of DOA

### ISSUE THREAD

**Issue by sunjunlishi** [jordi-adell/mcarray#5]
I find that the sound source is parallel to the horizontal plane of the microphone matrix, and the distance is a little far away. The more accurate the DOA is, the more stable it is ？

**Comment by sunjunlishi** [comment]
I probably understood your code structure 。
Data--（FFT）---FFTData
Loca(FFTData)   Separation(FFTData)
IFFT(FFTData)-->outData

**Comment by jordi-adell** [comment]
Right. This is the workflow.

**Comment by jordi-adell** [comment]
There is the far field assumption. If the source is too close it will not work.

**Comment by jordi-adell** [comment]
About a meter is the minimum. Though a bit closer might work too for certain sources.

**Comment by sunjunlishi** [comment]
thank you for your answer
